### ISSUE TITLE
Can't get 3 eigenvalues

### ISSUE THREAD

**Issue by j01993** [Skielex/structure-tensor#1]
import numpy as np
from structure_tensor import eig_special_3d, structure_tensor_3d

sigma = 1.5
rho = 5.5
volume = np.random.random((128, 128, 128))
S = structure_tensor_3d(volume, sigma, rho)
val, vec = eig_special_3d(S,full=True)

-------------------------------------------------------------------------------------------------------
if I run the above line, all the eigenvalues are the same (val[0,:,:,:]=val[1,:,:,:]=val[2,:,:,:]]). I want to get all 3 eigenvalues. How is it possible?

**Comment by Skielex** [comment]
The values should be different. Running the code I get:
```
In [8]: val[0,0,0,0]
Out[8]: 0.0002198562680121415

In [9]: val[1,0,0,0]
Out[9]: 0.0004318788496193132

In [10]: val[2,0,0,0]
Out[10]: 0.001042542575049389
```
Keep in mind you're just passing in random data, so the values will vary. Also, unless you need the two other eigenvectors, set ```full=False```. All three eigenvalues are always returned.

**Comment by j01993** [comment]
In my case, I get the same values. 

##

In [73]: val[0,0,0,0]
Out[73]: 0.0004921848426255371

In [74]: val[1,0,0,0]
Out[74]: 0.0004921848426255371

In [75]: val[2,0,0,0]
Out[75]: 0.0004921848426255371

##

I installed the package using pip install. I am using python 2.7 Could these be causing the error?

**Comment by Skielex** [comment]
I was able to reproduce the issue on Python 2.7 and numpy 1.16.6. I tried numpy 1.16.6 and Python 3.7.7, but here the values are correct (different).

My guess would be that some memory allocation in NumPy is handled differently in Python 2.7, but I don't know exactly where the problem lies. As Python 2.7 is being phased out and is not supported in the latest versions of NumPy and CuPy I don't want to spend too much time making our package Python 2 compatible.

I would suggest using Python 3 if possible. Otherwise you can probably resolve the issue by changing the code a little. Currently, we're reusing memory (numpy arrays) a lot during calculations to reduce memory usage, which may make the code a little more complex than otherwise necessary. If you find a good solution for supporting Python 2 you are more than welcome to share it.

**Comment by Skielex** [comment]
@j01993 , is there a particular reason you're using Python 2.7?

**Comment by j01993** [comment]
@Skielex Thanks. I was using Python 2.7 because some of the packages I use didn't upgrade to python 3. Now I checked that the package got an upgraded release.
